server:
  port: 8201
spring:
  application:
    name: eureka-feign
#开启hystrix断路器
feign:
  hystrix:
    enabled: true
#服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/