#服务注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/

server:
  port: 8202
spring:
  application:
    name: service-zuul

#指定连接路由转发
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-ribbon #以/api-a/ 开头的请求都转发给eureka-ribbon服务；
    api-b:
      path: /api-b/**
      serviceId: eureka-feign #以/api-b/开头的请求都转发给eureka-feign服务